name: ECS FARGATE

on:
 workflow_dispatch:
  
permissions:
  id-token: write
  contents: write
  repository-projects: write
  actions: write
  checks: write
  deployments: write

jobs:
  terraform-ECS-FARGATE:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: terraform-docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
         working-dir: usecase-8  # Use the current directory (adjust if needed)
         output-file: README.md  # Update the README file with generated docs
         output-method: inject  # Inject the documentation into the README
         git-push: "true"

         run: terraform-docs markdown table usecase-8 --output-file README.md --output-mode inject

         
      - name: Code checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: SetUp AWS OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.OIDC_ROLE }}
      

      - name: Run implement terraform
        run: |
          terraform init -reconfigure
          # terraform test
          # terraform fmt -recursive
          # terraform validate
          # terraform plan -var-file=terraform.tfvars
          # terraform apply -var-file=terraform.tfvars -auto-approve
          terraform destroy -var-file=terraform.tfvars -auto-approve
